name: monstar
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.1.2

  win32: ^2.5.0
  rive: ^0.13.13

  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1
  auto_route: ^7.8.3
  flutter_riverpod: ^2.5.1
  http: ^1.2.2

  delightful_toast: ^1.1.0
  image_picker: ^1.1.2
  get: ^4.6.6
  table_calendar: ^3.1.2
  animated_toggle_switch: ^0.8.3
  awesome_dialog: ^3.2.1
  flutter_secure_storage: ^4.2.1
  intl: ^0.19.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.3
  cached_network_image: ^3.4.1
  injectable: ^2.4.4
  injectable_generator: ^2.6.2
  flutter_gen: ^5.7.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  audioplayers: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_spinkit: ^5.2.1
  skeletonizer: ^1.4.2
  appinio_video_player: ^1.3.0
  video_player: ^2.6.0
  flick_video_player: ^0.5.0
  logger: ^2.4.0
  # flutter_login: ^5.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mocktail: ^1.0.4

  mockito: ^5.4.4
  auto_route_generator: ^7.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  flutter_gen_runner: ^5.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/rive/
    - assets/fonts/
    - assets/images/
    - assets/sound/click.mp3

  fonts:
    - family: CustomFontApp
      fonts:
        - asset: assets/fonts/Kalnia_Expanded-Light.ttf

    - family: BoldFontApp
      fonts:
        - asset: assets/fonts/Philosopher-Bold.ttf

    - family: RegularFontApp
      fonts:
        - asset: assets/fonts/Philosopher-Regular.ttf

    - family: DrawerFontApp
      fonts:
        - asset: assets/fonts/NerkoOne-Regular.ttf

    - family: ReadingFont
      fonts:
        - asset: assets/fonts/ComingSoon-Regular.ttf

    - family: SecureFont
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
    - family: AppFont
      fonts:
        - asset: assets/fonts/TenaliRamakrishna-Regular.ttf
